- quam/utils/config.py
- tests/config/test_config_final_actions.py
Analog output ports require an "offset" field by default (this will change in the future).
But for now, this was only supported for OPX+. Here I have added support for the LF-FEM of the OPX1000. 
It isn't needed for the MW-FEM, because the MW-FEM doesn't have any DC components.
> Fix: Add final action for setting offset of LF-FEM analog output port.

- CHANGELOG.md
- quam/serialisation/json.py
- tests/serialisation/test_json_serialisation.py
This PR modifies the JSONSerialiser to automatically convert JSON keys when the strings are actually ints.
Fixes #46
> add converter for int keys

- CHANGELOG.md
- quam/core/quam_instantiation.py
- tests/instantiation/test_instantiation.py
The code changes in `quam_instantiation.py` and `test_instantiation.py` introduce support for instantiating union types. This allows the `instantiate_attr` function to handle union types correctly when creating instances of classes. The changes include importing the `types` module and checking for `types.UnionType` in addition to `typing.Union` when determining if a type is a union type.
> feat: Add support for instantiating union types

- .github/workflows/release.yaml
- .github/workflows/reusable-build.yaml
- .github/workflows/reusable-buld.yaml
- pyproject.toml
[QUAL-276](https://quantum-machines.atlassian.net/browse/QUAL-276)
> ci: create draft release on push tag

- CHANGELOG.md
- quam/components/channels.py
- quam/components/pulses.py
- tests/components/channels/test_IQ_channel.py
- tests/components/channels/test_in_IQ_out_single_channel.py
- tests/components/channels/test_in_single_channel.py
- tests/components/channels/test_in_single_out_IQ_channel.py
- tests/components/test_octave.py
This PR adds the following changes
- Add missing attributes to `MWChannel`
- Make `Channel` an abstract base class
- Move `intermediate_frequency` to `Channel`, meaning that all channels share this property
- Add `smearing`, `time_of_flight`
> Fix/Add all MW channel properties

- quam/components/channels.py
Fixed the config builder in the `MWChannel` components according to the syntax for `qm-qua==1.2.1rc3`
@nulinspiratie @KevinAVR
> Fix syntax for MW channel attributes.

- quam/components/ports/analog_outputs.py
- tests/components/ports/test_lf_fem_analog_ports.py
This only happens when `port.sampling_rate != 1e9`. Otherwise an error is raised during config validation
> Fix: Remove upsampling mode for LFFEMAnalogOutputPort

- .github/workflows/release_github.yaml
- .github/workflows/release_pypi.yaml
[QUAL-643](https://quantum-machines.atlassian.net/browse/QUAL-643)
> Release package to PyPI

- CHANGELOG.md
- quam/components/channels.py
- tests/components/channels/test_mw_channel.py
For OPX+/OPX1000 dynamic code, we would like the `IQChannel` and `MWChannel` to share a common interface for accessing the upconverter frequency field.
Although this approach matches the convention used in the `IQChannel`, I'm indifferent to how the property looks at the end of the day, as long as the upconverter frequency can be accessed the same way between both channel types.
@nulinspiratie @KevinAVR
> Abstraction for LO frequency to MWChannel that matches the IQChannel

- CHANGELOG.md
- docs/components/channels.md
- docs/components/pulses.md
- quam/components/channels.py
- tests/components/channels/test_in_single_channel.py
- tests/components/channels/test_in_single_out_IQ_channel.py
- tests/components/channels/test_time_tagging.py
Time tagging can be performed as follows:
**Step 1: Add `TimeTaggingAddon` to channel**
```python
channel.time_tagging = TimeTaggingAddon(signal_threshold=0.2, ...)
```
**Step 2: Perform time tagging**
```python
times, counts = channel.measure_time_tagging("readout", size=1000, max_time=800)
```
> Feat: Add time tagging to channels

- CHANGELOG.md
- quam/components/channels.py
- quam/components/pulses.py
- tests/components/pulses/test_pulse_weights.py
Adds `ReadoutPulse.default_integration_weights` property that returns `[(1, pulse.length)]`
Fixes #54
> Feat: Add default integration weights

- CHANGELOG.md
- quam/core/quam_classes.py
- quam/utils/reference_class.py
- quam/utils/string_reference.py
- tests/quam_base/test_set_at_reference.py
- tests/utils/test_string_reference.py
This PR adds a new method that allows setting values at the target of a reference rather than modifying the reference itself. This is useful when you want to update the actual referenced value through a reference attribute.
Fixes #85 
```python
class MyQuam(QuamRoot):
a: int
b: str
quam = MyQuam(a=5, b="#./a")  # b references a's value
quam.b = 10  # This would break the reference by setting b directly to 10
quam.set_at_reference("b", 10)  # This follows the reference and sets a to 10
assert quam.a == 10  # a was updated
assert quam.b == 10  # b still references a and shows the new value
```
> Feat/Add `QuamBase.set_at_reference`

- CHANGELOG.md
- quam/core/quam_classes.py
- quam/utils/string_reference.py
- tests/quam_base/referencing/test_get_reference_relative_path.py
- tests/quam_base/referencing/test_reference_path.py
- tests/utils/test_join_references.py
This PR introduces the kwarg `relative_path` to `QuamBase.get_references()`
This enables the user to retrieve a relative reference w.r.t. a specific QUAM component
Closes #98 
We assume a QuamRoot object with a component "elem".
- `elem.get_reference() == "#/elem"`
- `elem.get_reference(attr="child") == "#/elem/child"`
- `elem.get_reference(relative_path="#./child") == "#/elem/child"`
- `elem.get_reference(relative_path="#../child") == "#/child"`
- `elem.get_reference(relative_path="#./child/grandchild") == "#/elem/child/grandchild"`
> Feat: Add `relative_path` to `QuamBase.get_references`

- CHANGELOG.md
- quam/core/quam_classes.py
@JacobHast do you see this warning, or is it filtered by the logs?
> Fix: Add error message when multiple QuamRoot objects are instantiated

- quam/components/channels.py
> Fix: Update typing for channel output/input ports

- CHANGELOG.md
- quam/components/octave.py
- quam/core/quam_classes.py
- tests/components/test_octave.py
- tests/config/test_config_settings.py
- tests/conftest.py
- tests/examples/superconducting_qubits/test_transmon.py
- tests/quam_base/referencing/test_quam_class_referencing.py
- tests/quam_base/referencing/test_reference_path.py
- tests/quam_base/referencing/test_referencing_list.py
- tests/quam_base/test_multiple_quam.py
- tests/quam_base/test_quam_base.py
This PR introduces support for multiple QuamRoot objects.
Previously, the active QuamRoot object was tracked using the class attribute `QuamBase._root`, which is overridden if a new QuamRoot object is created.
In the new implementation, the QuamRoot is determined through `QuamComponent.get_root()`, which recursively follows the parent chain until it finds a QuamRoot. If no QuamRoot is found it returns None.
For backwards compatibility, if the parent chain does not end in a QuamRoot, it will check if a QuamRoot has been instantiated, and if so, return the latest one.
Warnings are still raised if multiple QuamRoot objects are instantiated, and also if a component does not have a QuamRoot in its parent chain
@JacobHast should cover issue #58
> Feat: Support multiple QuamRoot objects

- CHANGELOG.md
- quam/components/channels.py
- Added `upconverter_frequency` property to correctly handle upconverter frequency
- Support retrieving frequency from both `upconverter_frequency` and `upconverters` specifications
- Updated CHANGELOG.md to reflect the fix
> Fix: Improve upconverter frequency retrieval in MWChannel

- docs/components/index.md
The link on the github pages leads to a 404 error: https://qua-platform.github.io/quam/components/#custom-quam-components
The PR makes it relative like all the other links in the document.
> Fix wrong link in docs

- CHANGELOG.md
- quam/components/channels.py
- quam/components/ports/analog_outputs.py
- tests/components/ports/test_lf_fem_analog_ports.py
Adds `LFFEMAnalogOutputPort.exponential_filter` and `LFFEMAnalogOutputPort.high_pass_filter`.
Currently there are no checks that discriminate between QOP version
> Change: new filters that comply with QOP 3.3

- CHANGELOG.md
- quam/components/quantum_components/qubit.py
- quam/components/quantum_components/qubit_pair.py
- quam/core/macro/quam_macro.py
- quam/core/quam_classes.py
- quam/utils/reference_class.py
- tests/components/pulses/test_pulses.py
- tests/quam_base/test_quam_dict.py
- tests/quam_base/test_set_at_reference.py
The QUAM method `get_unreferenced_value` naming was found to be confusing. The method has therefore been renamed to `get_raw_value`.
The method `get_unreferenced_value` still exists, but now raises a deprecation warning and redirects to `get_raw_value`
Also addresses #127 @JacobHast
> Change: Deprecate `get_unreferenced_value` in favor of `get_raw_value`

- CHANGELOG.md
- quam/core/quam_classes.py
- tests/quam_base/test_quam_base.py
The functions `QuamDict/QuamComponent.get_attr_name()` did not take into account that its attributes could be references. As a result, some things such as extracting the proper references and performing state updates could fail.
For example, this used to fail:
```python
d = QuamDict(a="#./b", b={"value": 42})
assert d.a is d.b
assert d.get_attr_name(d.b) == "b"
```
> Fix: get_attr_name fails with references

- pyproject.toml
- Updated qm-qua minimum version requirement from 1.1.0 to 1.2.2
- Added prerelease = "allow" configuration under [tool.uv] section
- **pyproject.toml**: Updated `qm-qua` dependency version and added UV prerelease configuration
> Update min qm-qua version ≥ 1.22 and add prerelease allow

- CHANGELOG.md
- quam/components/channels.py
This PR updates all `measure()` calls in channels.py to be compatible with the new QM-QUA version.
In the latest QM-QUA version, the `measure()` function syntax has changed:
- **Old syntax**: `measure(pulse, element, stream, demod1, demod2, ...)`  
- **New syntax**: `measure(pulse, element, demod1, demod2, ..., adc_stream=stream)`
The stream parameter is no longer accepted as a positional argument and must be passed as an explicit keyword argument.
- **quam/components/channels.py**: Updated 7 different `measure()` call locations across multiple channel classes:
- `_InComplexChannel.measure()` (line 869)
- `_InComplexChannel.measure_accumulated()` (line 952) 
- `_InComplexChannel.measure_sliced()` (line 1035)
- `_InComplexChannel.measure_time_tagging()` (line 1094)
- …
> Update measure calls for QM-QUA 1.2.2 compatibility
